### ISSUE TITLE
Missing metabolites in the LCM .BASIS file

### ISSUE THREAD

**Issue by martin3141** [shui5/MRSCloud#2]
Hi,

Just getting started with this, but already looks like a really useful resource!

I tried simulating a basic PRESS sequence at mricloud.org. The correct list of .mat files were generated, but the LCModel .BASIS file had two missing (mI and sI). 

configure_out.json listed below:

{
    "userInput": {
        "metablist": [
            "Ala",
            "GABA",
            "Lac",
            "Phenyl",
            "bHB",
            "Asc",
            "GPC",
            "mI",
            "Ser",
            "Asp",
            "GSH",
            "NAA",
            "sI",
            "Cit",
            "Gln",
            "NAAG",
            "Tau",
            "Cr",
            "Glu",
            "PCh",
            "Thr",
            "EA",
            "Gly",
            "PCr",
            "Tyros",
            "EtOH",
            "H2O",
            "PE",
            "Val"
        ],
        "vendor": [
            "Philips"
        ],
        "mega_or_hadam": [
            "UnEdited"
        ],
        "localization": [
            "PRESS"
        ],
        "editTarget": [
            "GABA"
        ],
        "TE": 37,
        "editOn": 1.9,
        "editOff": 7.5,
        "editTp": 14,
        "spatial_points": 101,
        "email_address": "removed"
    },
    "private": {
        "metab_default": [
            "Cr",
            "NAA"
        ],
        "metab_default_2": [
            "H2O"
        ],
        "flipAngle": 180,
        "centreFreq": 3,
        "edit_flipAngle": 180
    },
    "DIRECTORY": {
    }
}

Any idea what went wrong?

Thanks for your help,

Martin

**Comment by shui5** [comment]
Dear Martin,

Thanks for your message.
Someone has pointed out the same issue. It was the naming convention for myo inositol and scyllo inositol. We previously used Ins and Scyllo as the file names in the spin system and now we have changed them to mI and sI. However, part of the code remained using the old ones. We have fixed the issue and will update MRSCloud asap.

Steve

**Comment by martin3141** [comment]
Hi Steve,

Thanks for the response. Good to hear a fix is on the way!

Best wishes,

Martin
